version: "3"

services:
  database:
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "grumpy_cat_prod"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network
  backend:
    build: backend/
    ports:
      - "4000:4000"
    depends_on:
      - database
    networks:
      - db_network
    environment:
      PORT: 4000
  frontend:
    build: frontend/
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:

networks:
  db_network:
    driver: bridge
